version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          build: 'npm run build'
          working_directory: '~/project/cypress'
      - cypress/run:
          requires:
            - cypress/install
          record: false 
          parallel: true
          parallelism: 4 
          group: 'all tests' 
          start: 'npm start' 
          working_directory: '~/project/app'